name: Release Application

on:
  push:
    branches:
    - '**'

env:
  OPENSHIFT_SERVER: "https://api.sandbox-m2.ll9k.p1.openshiftapps.com:6443"
  OPENSHIFT_NAMESPACE: "ignace-mella-a-dev"

jobs:
  deploy:
    if: github.ref == 'refs/heads/dev'
    environment: development
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
    - name: Apply Openshift YAML
      run: |
        kubectl apply -f openshift.yaml -n ignace-mella-a-dev